import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Navbar } from "@/components/Navbar";
import { apiFetch } from "@/lib/api";

export const Route = createFileRoute("/seller-marketplace")({ head: () => ({ meta: [{ title: "Seller Marketplace — AgriSaathi" }] }), component: SellerMarketplace });
function SellerMarketplace() {
  const [user, setUser] = useState<any>(null); const [products, setProducts] = useState<any[]>([]); const [error, setError] = useState("");
  const [form, setForm] = useState({ product_name: "", price_per_kg: "", quantity_available: "", date_of_harvest: "" });
  const load = (id: number) => apiFetch<any[]>(`/sellers/${id}/products`).then(setProducts).catch((e) => setError(e.message));
  useEffect(() => { const u = JSON.parse(localStorage.getItem("agrisaathi_user") || "null"); setUser(u); if (u?.seller_id) load(u.seller_id); }, []);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (!user?.seller_id) return; try { await apiFetch(`/sellers/${user.seller_id}/products`, { method: "POST", body: JSON.stringify(form) }); setForm({ product_name: "", price_per_kg: "", quantity_available: "", date_of_harvest: "" }); load(user.seller_id); } catch (e: any) { setError(e.message); } };
  return <main className="min-h-screen bg-background"><Navbar /><div className="mx-auto max-w-6xl px-5 pb-20 pt-32"><h1 className="text-4xl font-extrabold">Seller Marketplace</h1>{!user?.seller_id ? <p className="mt-4 text-muted-foreground">Please login as a seller to list your harvest.</p> : <><p className="mt-2 text-muted-foreground">Welcome, {user.name}. List harvest directly for consumers and bulk buyers.</p><form onSubmit={submit} className="mt-8 grid gap-4 rounded-2xl border border-border bg-card p-5 sm:grid-cols-4"><input className="rounded-lg border p-3" placeholder="Product name" value={form.product_name} onChange={e => setForm({...form, product_name:e.target.value})} required/><input className="rounded-lg border p-3" type="number" step="0.01" placeholder="₹ / kg" value={form.price_per_kg} onChange={e => setForm({...form, price_per_kg:e.target.value})} required/><input className="rounded-lg border p-3" type="number" step="0.01" placeholder="Quantity (kg)" value={form.quantity_available} onChange={e => setForm({...form, quantity_available:e.target.value})} required/><input className="rounded-lg border p-3" type="date" value={form.date_of_harvest} onChange={e => setForm({...form, date_of_harvest:e.target.value})} required/><button className="rounded-lg bg-primary p-3 font-semibold text-primary-foreground sm:col-span-4">List Product</button></form><h2 className="mt-10 text-2xl font-bold">Your Listings</h2><div className="mt-4 grid gap-3">{products.map(p => <div key={p.product_id} className="flex items-center justify-between rounded-xl border border-border bg-card p-4"><div><b>{p.product_name}</b><p className="text-sm text-muted-foreground">Harvest: {p.date_of_harvest} · {p.quantity_available} kg</p></div><b>₹{p.price_per_kg}/kg</b></div>)}</div></>}{error && <p className="mt-4 text-sm text-destructive">{error}</p>}</div></main>;
}
