/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as FarmersRouteImport } from './routes/farmers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as SellerMarketplaceRouteImport } from './routes/seller-marketplace'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WishlistRouteImport } from './routes/wishlist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersRoute = FarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerMarketplaceRoute = SellerMarketplaceRouteImport.update({
  id: '/seller-marketplace',
  path: '/seller-marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/farmers': typeof FarmersRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/seller-marketplace': typeof SellerMarketplaceRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/farmers': typeof FarmersRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/seller-marketplace': typeof SellerMarketplaceRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/farmers': typeof FarmersRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/seller-marketplace': typeof SellerMarketplaceRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/farmers'
    | '/login'
    | '/marketplace'
    | '/messages'
    | '/offers'
    | '/orders'
    | '/seller-marketplace'
    | '/signup'
    | '/support'
    | '/wishlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/farmers'
    | '/login'
    | '/marketplace'
    | '/messages'
    | '/offers'
    | '/orders'
    | '/seller-marketplace'
    | '/signup'
    | '/support'
    | '/wishlist'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/farmers'
    | '/login'
    | '/marketplace'
    | '/messages'
    | '/offers'
    | '/orders'
    | '/seller-marketplace'
    | '/signup'
    | '/support'
    | '/wishlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  FarmersRoute: typeof FarmersRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRoute
  OffersRoute: typeof OffersRoute
  OrdersRoute: typeof OrdersRoute
  SellerMarketplaceRoute: typeof SellerMarketplaceRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  WishlistRoute: typeof WishlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers': {
      id: '/farmers'
      path: '/farmers'
      fullPath: '/farmers'
      preLoaderRoute: typeof FarmersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-marketplace': {
      id: '/seller-marketplace'
      path: '/seller-marketplace'
      fullPath: '/seller-marketplace'
      preLoaderRoute: typeof SellerMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  FarmersRoute: FarmersRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRoute,
  OffersRoute: OffersRoute,
  OrdersRoute: OrdersRoute,
  SellerMarketplaceRoute: SellerMarketplaceRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  WishlistRoute: WishlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
